/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { DBContext } from "./../context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * UTC Date-time
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "CsDateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * UTC Date-time
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "CsDateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  MFBookUpsertInput: { // input type
    authorId?: number | null; // Int
    chapters?: NexusGenInputs['MFChapterUpsertInput'][] | null; // [MFChapterUpsertInput!]
    description: string; // String!
    genre: string; // String!
    id?: number | null; // Int
    image?: string | null; // String
    locationId?: number | null; // Int
    order?: number | null; // Int
    price?: number | null; // Float
    public?: boolean | null; // Boolean
    seriesId?: number | null; // Int
    title: string; // String!
    worldId?: number | null; // Int
  }
  MFChapterUpsertInput: { // input type
    authorId?: number | null; // Int
    bookId: number; // Int!
    description?: string | null; // String
    id?: number | null; // Int
    image?: string | null; // String
    order?: number | null; // Int
    scenes?: NexusGenInputs['MFSceneUpsertInput'][] | null; // [MFSceneUpsertInput!]
    title: string; // String!
  }
  MFCharacterUpsertInput: { // input type
    authorId?: number | null; // Int
    description: string | null; // String
    groupId?: number | null; // Int
    id?: number | null; // Int
    image?: string | null; // String
    locationId?: number | null; // Int
    name: string; // String!
    worldId: number; // Int!
  }
  MFContentLinkUpsertInput: { // input type
    authorId?: number | null; // Int
    bookId: number; // Int!
    chapterId?: number | null; // Int
    id?: number | null; // Int
    originId: number; // Int!
    sceneId?: number | null; // Int
    seriesId?: number | null; // Int
    text: string; // String!
  }
  MFEventUpsertInput: { // input type
    authorId?: number | null; // Int
    characterId?: number | null; // Int
    description: string | null; // String
    groupId?: number | null; // Int
    id?: number | null; // Int
    locationId?: number | null; // Int
    name: string; // String!
    polarity: NexusGenEnums['EventPolarity']; // EventPolarity!
    target: NexusGenEnums['EventTarget']; // EventTarget!
    worldId: number; // Int!
  }
  MFExplorationSceneUpsertInput: { // input type
    authorId?: number | null; // Int
    background?: string | null; // String
    characters?: string | null; // String
    config?: string | null; // String
    description?: string | null; // String
    explorationId?: number | null; // Int
    foreground?: string | null; // String
    id?: number | null; // Int
    order: number; // Int!
    title: string; // String!
  }
  MFExplorationUpsertInput: { // input type
    Scenes?: NexusGenInputs['MFExplorationSceneUpsertInput'][] | null; // [MFExplorationSceneUpsertInput!]
    authorId?: number | null; // Int
    config?: string | null; // String
    description?: string | null; // String
    id?: number | null; // Int
    image?: string | null; // String
    locationId?: number | null; // Int
    price?: number | null; // Float
    public?: boolean | null; // Boolean
    publishDate?: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    title: string; // String!
    usesAttributes?: string | null; // String
    worldId: number; // Int!
  }
  MFGroupUpsertInput: { // input type
    authorId?: number | null; // Int
    description: string; // String!
    id?: number | null; // Int
    name: string; // String!
    type: NexusGenEnums['GroupType']; // GroupType!
    worldId: number; // Int!
  }
  MFLocationUpsertInput: { // input type
    authorId?: number | null; // Int
    climate?: NexusGenEnums['Climate'] | null; // Climate
    description: string; // String!
    eastOf?: number | null; // Int
    fauna?: NexusGenEnums['Richness'] | null; // Richness
    flora?: NexusGenEnums['Richness'] | null; // Richness
    id?: number | null; // Int
    image?: string | null; // String
    name: string; // String!
    northOf?: number | null; // Int
    parentLocationId?: number | null; // Int
    southOf?: number | null; // Int
    type: NexusGenEnums['LocationType']; // LocationType!
    westOf?: number | null; // Int
    worldId: number; // Int!
  }
  MFRelationshipUpsertInput: { // input type
    authorId?: number | null; // Int
    characterId: number; // Int!
    id?: number | null; // Int
    relationship: string; // String!
    targetId: number; // Int!
  }
  MFSceneUpsertInput: { // input type
    authorId?: number | null; // Int
    chapterId: number; // Int!
    characterId?: number | null; // Int
    description?: string | null; // String
    eventContextId?: number | null; // Int
    id?: number | null; // Int
    image?: string | null; // String
    order: number; // Int!
    text: string; // String!
    timelineId?: number | null; // Int
    title: string; // String!
  }
  MFSeriesUpsertInput: { // input type
    authorId?: number | null; // Int
    books?: NexusGenInputs['MFBookUpsertInput'][] | null; // [MFBookUpsertInput!]
    description: string; // String!
    genre: string; // String!
    id?: number | null; // Int
    image?: string | null; // String
    price?: number | null; // Float
    public?: boolean | null; // Boolean
    title: string; // String!
  }
  MFTimelineEventUpsertInput: { // input type
    authorId?: number | null; // Int
    eventId: number; // Int!
    id?: number | null; // Int
    order: number; // Int!
    timelineId: number; // Int!
  }
  MFTimelineUpsertInput: { // input type
    authorId?: number | null; // Int
    events?: NexusGenInputs['MFTimelineEventUpsertInput'][] | null; // [MFTimelineEventUpsertInput!]
    id?: number | null; // Int
    name: string; // String!
    worldId: number; // Int!
  }
  MFUserUpsertInput: { // input type
    displayName?: string | null; // String
    email?: string | null; // String
    firstName?: string | null; // String
    image?: string | null; // String
    lastName?: string | null; // String
    password?: string | null; // String
  }
  MFWorldUpsertInput: { // input type
    authorId?: number | null; // Int
    description: string; // String!
    id?: number | null; // Int
    image?: string | null; // String
    name: string; // String!
    parentWorldId?: number | null; // Int
    public?: boolean | null; // Boolean
    type: NexusGenEnums['WorldType']; // WorldType!
  }
}

export interface NexusGenEnums {
  Authenticator: "google" | "magic" | "other"
  ChapterStatus: "Archived" | "Draft" | "Published"
  Climate: "Polar" | "Temperate" | "Unspecified" | "Warm"
  EventPolarity: "NegativeExpected" | "NegativeUnexpected" | "Neutral" | "PositiveExpected" | "PositiveUnexpected"
  EventTarget: "Local" | "Person" | "World"
  GroupType: "Culture" | "Other" | "Philosophy" | "Trade"
  LocationType: "Building" | "City" | "Continent" | "Country" | "Other" | "Region" | "Ruins" | "Settlement" | "Town" | "Village"
  Richness: "Abundant" | "Adequate" | "Barren" | "Sparse" | "Unspecified"
  UserRole: "Admin" | "Author" | "Moderator" | "Reader"
  WorldType: "Galaxy" | "Other" | "Planet" | "Realm" | "Star" | "Universe"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  CsDateTime: any
}

export interface NexusGenObjects {
  MFAuthor: { // root type
    Books?: Array<NexusGenRootTypes['MFBook'] | null> | null; // [MFBook]
    Series?: Array<NexusGenRootTypes['MFSeries'] | null> | null; // [MFSeries]
    Timelines?: Array<NexusGenRootTypes['MFTimeline'] | null> | null; // [MFTimeline]
    Worlds?: Array<NexusGenRootTypes['MFWorld'] | null> | null; // [MFWorld]
    displayName: string; // String!
    email: string; // String!
    firstName?: string | null; // String
    id: number; // Int!
    image?: string | null; // String
    lastName?: string | null; // String
    role?: NexusGenEnums['UserRole'] | null; // UserRole
  }
  MFBook: { // root type
    Author?: NexusGenRootTypes['MFAuthor'] | null; // MFAuthor
    Chapters?: Array<NexusGenRootTypes['MFChapter'] | null> | null; // [MFChapter]
    authorId?: number | null; // Int
    created?: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    description: string; // String!
    genre: string; // String!
    id: number; // Int!
    image?: string | null; // String
    locationId?: number | null; // Int
    order?: number | null; // Int
    price?: number | null; // Float
    public: boolean; // Boolean!
    publishDate?: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    seriesId?: number | null; // Int
    title: string; // String!
    updated?: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    worldId?: number | null; // Int
  }
  MFChapter: { // root type
    Author?: NexusGenRootTypes['MFAuthor'] | null; // MFAuthor
    Links?: Array<NexusGenRootTypes['MFSceneContentLink'] | null> | null; // [MFSceneContentLink]
    Scenes?: Array<NexusGenRootTypes['MFScene'] | null> | null; // [MFScene]
    authorId?: number | null; // Int
    bookId?: number | null; // Int
    created?: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    description?: string | null; // String
    id: number; // Int!
    image?: string | null; // String
    order: number; // Int!
    status?: NexusGenEnums['ChapterStatus'] | null; // ChapterStatus
    title: string; // String!
    updated?: NexusGenScalars['CsDateTime'] | null; // CsDateTime
  }
  MFCharacter: { // root type
    CharacterRelationship?: Array<NexusGenRootTypes['MFCharacterRelationship'] | null> | null; // [MFCharacterRelationship]
    World?: NexusGenRootTypes['MFWorld'] | null; // MFWorld
    authorId?: number | null; // Int
    description: string; // String!
    groupId?: number | null; // Int
    id: number; // Int!
    image?: string | null; // String
    locationId?: number | null; // Int
    name: string; // String!
    worldId: number; // Int!
  }
  MFCharacterRelationship: { // root type
    Character?: NexusGenRootTypes['MFCharacter'] | null; // MFCharacter
    characterId: number; // Int!
    id: number; // Int!
    relationship: string; // String!
    targetId: number; // Int!
  }
  MFEvent: { // root type
    World?: NexusGenRootTypes['MFWorld'] | null; // MFWorld
    authorId?: number | null; // Int
    characterId?: number | null; // Int
    description?: string | null; // String
    groupId?: number | null; // Int
    id: number; // Int!
    locationId?: number | null; // Int
    name: string; // String!
    polarity: NexusGenEnums['EventPolarity']; // EventPolarity!
    target: NexusGenEnums['EventTarget']; // EventTarget!
    worldId: number; // Int!
  }
  MFExploration: { // root type
    Author?: NexusGenRootTypes['MFAuthor'] | null; // MFAuthor
    Location?: NexusGenRootTypes['MFLocation'] | null; // MFLocation
    Scenes: Array<NexusGenRootTypes['MFExplorationScene'] | null>; // [MFExplorationScene]!
    World?: NexusGenRootTypes['MFWorld'] | null; // MFWorld
    authorId?: number | null; // Int
    config?: string | null; // String
    created?: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    description?: string | null; // String
    id: number; // Int!
    image?: string | null; // String
    lastUpdated?: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    locationId?: number | null; // Int
    price?: number | null; // Float
    public?: boolean | null; // Boolean
    publishDate?: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    title: string; // String!
    usesAttributes?: string | null; // String
    worldId: number; // Int!
  }
  MFExplorationScene: { // root type
    Exploration?: NexusGenRootTypes['MFExploration'] | null; // MFExploration
    authorId?: number | null; // Int
    background?: string | null; // String
    characters?: string | null; // String
    config?: string | null; // String
    description?: string | null; // String
    explorationId: number; // Int!
    foreground?: string | null; // String
    id: number; // Int!
    order: number; // Int!
    title: string; // String!
  }
  MFLibrary: { // root type
    Book?: NexusGenRootTypes['MFBook'] | null; // MFBook
    Exploration?: NexusGenRootTypes['MFExploration'] | null; // MFExploration
    Series?: NexusGenRootTypes['MFSeries'] | null; // MFSeries
    bookId?: number | null; // Int
    explorationId?: number | null; // Int
    id: number; // Int!
    order: number; // Int!
    publicPurchase: boolean; // Boolean!
    purchaseDate?: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    seriesId?: number | null; // Int
    userId: number; // Int!
  }
  MFLocation: { // root type
    Characters?: Array<NexusGenRootTypes['MFCharacter'] | null> | null; // [MFCharacter]
    Events?: Array<NexusGenRootTypes['MFEvent'] | null> | null; // [MFEvent]
    Groups?: Array<NexusGenRootTypes['MFPopulationGroup'] | null> | null; // [MFPopulationGroup]
    World?: NexusGenRootTypes['MFWorld'] | null; // MFWorld
    authorId?: number | null; // Int
    climate?: NexusGenEnums['Climate'] | null; // Climate
    description: string; // String!
    fauna?: NexusGenEnums['Richness'] | null; // Richness
    flora?: NexusGenEnums['Richness'] | null; // Richness
    id: number; // Int!
    name: string; // String!
    parentLocationId?: number | null; // Int
    type: NexusGenEnums['LocationType']; // LocationType!
    worldId: number; // Int!
  }
  MFPopulationGroup: { // root type
    Character?: Array<NexusGenRootTypes['MFCharacter'] | null> | null; // [MFCharacter]
    Event?: Array<NexusGenRootTypes['MFEvent'] | null> | null; // [MFEvent]
    authorId?: number | null; // Int
    description: string; // String!
    id: number; // Int!
    locationId?: number | null; // Int
    name: string; // String!
    type: NexusGenEnums['GroupType']; // GroupType!
    worldId: number; // Int!
  }
  MFScene: { // root type
    Links?: Array<NexusGenRootTypes['MFSceneContentLink'] | null> | null; // [MFSceneContentLink]
    authorId?: number | null; // Int
    chapterId: number; // Int!
    characterId?: number | null; // Int
    created?: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    description?: string | null; // String
    eventContextId?: number | null; // Int
    id: number; // Int!
    image?: string | null; // String
    order: number; // Int!
    text?: string | null; // String
    timelineId?: number | null; // Int
    title: string; // String!
    updated?: NexusGenScalars['CsDateTime'] | null; // CsDateTime
  }
  MFSceneContentLink: { // root type
    authorId?: number | null; // Int
    bookId: number; // Int!
    chapterId?: number | null; // Int
    id: number; // Int!
    originId: number; // Int!
    sceneId?: number | null; // Int
    seriesId?: number | null; // Int
    text: string; // String!
  }
  MFSearchResult: { // root type
    books: Array<NexusGenRootTypes['MFBook'] | null>; // [MFBook]!
    series: Array<NexusGenRootTypes['MFSeries'] | null>; // [MFSeries]!
  }
  MFSeries: { // root type
    Author?: NexusGenRootTypes['MFAuthor'] | null; // MFAuthor
    Books: Array<NexusGenRootTypes['MFBook'] | null>; // [MFBook]!
    authorId?: number | null; // Int
    created?: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    description: string; // String!
    genre: string; // String!
    id: number; // Int!
    image?: string | null; // String
    price?: number | null; // Float
    public: boolean; // Boolean!
    publishDate?: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    title: string; // String!
    updated?: NexusGenScalars['CsDateTime'] | null; // CsDateTime
  }
  MFTimeline: { // root type
    Author?: NexusGenRootTypes['MFAuthor'] | null; // MFAuthor
    Scenes?: Array<NexusGenRootTypes['MFScene'] | null> | null; // [MFScene]
    TimelineEvents?: Array<NexusGenRootTypes['MFTimelineEvent'] | null> | null; // [MFTimelineEvent]
    World?: NexusGenRootTypes['MFWorld'] | null; // MFWorld
    authorId?: number | null; // Int
    id: number; // Int!
    name: string; // String!
    worldId: number; // Int!
  }
  MFTimelineEvent: { // root type
    Event?: NexusGenRootTypes['MFEvent'] | null; // MFEvent
    Scenes?: Array<NexusGenRootTypes['MFScene'] | null> | null; // [MFScene]
    authorId?: number | null; // Int
    eventId: number; // Int!
    id: number; // Int!
    order: number; // Int!
    timelineId: number; // Int!
  }
  MFUser: { // root type
    Books?: Array<NexusGenRootTypes['MFBook'] | null> | null; // [MFBook]
    Characters?: Array<NexusGenRootTypes['MFCharacter'] | null> | null; // [MFCharacter]
    Series?: Array<NexusGenRootTypes['MFSeries'] | null> | null; // [MFSeries]
    Timelines?: Array<NexusGenRootTypes['MFTimeline'] | null> | null; // [MFTimeline]
    Worlds?: Array<NexusGenRootTypes['MFWorld'] | null> | null; // [MFWorld]
    authSource: NexusGenEnums['Authenticator']; // Authenticator!
    created: NexusGenScalars['CsDateTime']; // CsDateTime!
    displayName: string; // String!
    email: string; // String!
    firstName?: string | null; // String
    id: number; // Int!
    image?: string | null; // String
    lastName?: string | null; // String
    lastSeen: NexusGenScalars['CsDateTime']; // CsDateTime!
    role: NexusGenEnums['UserRole']; // UserRole!
  }
  MFWorld: { // root type
    Events?: Array<NexusGenRootTypes['MFEvent'] | null> | null; // [MFEvent]
    Groups?: Array<NexusGenRootTypes['MFPopulationGroup'] | null> | null; // [MFPopulationGroup]
    Locations?: Array<NexusGenRootTypes['MFLocation'] | null> | null; // [MFLocation]
    Timelines?: Array<NexusGenRootTypes['MFTimeline'] | null> | null; // [MFTimeline]
    authorId?: number | null; // Int
    description: string; // String!
    id: number; // Int!
    image?: string | null; // String
    name: string; // String!
    parentWorldId?: number | null; // Int
    public: boolean; // Boolean!
    type: NexusGenEnums['WorldType']; // WorldType!
  }
  Mutation: {};
  Note: { // root type
    Author?: NexusGenRootTypes['MFAuthor'] | null; // MFAuthor
    Book?: NexusGenRootTypes['MFBook'] | null; // MFBook
    Chapter?: NexusGenRootTypes['MFChapter'] | null; // MFChapter
    Character?: NexusGenRootTypes['MFCharacter'] | null; // MFCharacter
    Scene?: NexusGenRootTypes['MFScene'] | null; // MFScene
    authorId: number; // Int!
    bookId?: number | null; // Int
    chapterId?: number | null; // Int
    characterId?: number | null; // Int
    description: string; // String!
    id: number; // Int!
    image?: string | null; // String
    sceneId?: number | null; // Int
    title: string; // String!
  }
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  MFAuthor: { // field return type
    Books: Array<NexusGenRootTypes['MFBook'] | null> | null; // [MFBook]
    Series: Array<NexusGenRootTypes['MFSeries'] | null> | null; // [MFSeries]
    Timelines: Array<NexusGenRootTypes['MFTimeline'] | null> | null; // [MFTimeline]
    Worlds: Array<NexusGenRootTypes['MFWorld'] | null> | null; // [MFWorld]
    displayName: string; // String!
    email: string; // String!
    firstName: string | null; // String
    id: number; // Int!
    image: string | null; // String
    lastName: string | null; // String
    role: NexusGenEnums['UserRole'] | null; // UserRole
  }
  MFBook: { // field return type
    Author: NexusGenRootTypes['MFAuthor'] | null; // MFAuthor
    Chapters: Array<NexusGenRootTypes['MFChapter'] | null> | null; // [MFChapter]
    authorId: number | null; // Int
    created: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    description: string; // String!
    free: boolean | null; // Boolean
    genre: string; // String!
    id: number; // Int!
    image: string | null; // String
    locationId: number | null; // Int
    order: number | null; // Int
    price: number | null; // Float
    public: boolean; // Boolean!
    publishDate: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    seriesId: number | null; // Int
    title: string; // String!
    updated: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    worldId: number | null; // Int
  }
  MFChapter: { // field return type
    Author: NexusGenRootTypes['MFAuthor'] | null; // MFAuthor
    Links: Array<NexusGenRootTypes['MFSceneContentLink'] | null> | null; // [MFSceneContentLink]
    Scenes: Array<NexusGenRootTypes['MFScene'] | null> | null; // [MFScene]
    authorId: number | null; // Int
    bookId: number | null; // Int
    created: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    description: string | null; // String
    id: number; // Int!
    image: string | null; // String
    order: number; // Int!
    status: NexusGenEnums['ChapterStatus'] | null; // ChapterStatus
    title: string; // String!
    updated: NexusGenScalars['CsDateTime'] | null; // CsDateTime
  }
  MFCharacter: { // field return type
    CharacterRelationship: Array<NexusGenRootTypes['MFCharacterRelationship'] | null> | null; // [MFCharacterRelationship]
    World: NexusGenRootTypes['MFWorld'] | null; // MFWorld
    authorId: number | null; // Int
    description: string; // String!
    groupId: number | null; // Int
    id: number; // Int!
    image: string | null; // String
    locationId: number | null; // Int
    name: string; // String!
    worldId: number; // Int!
  }
  MFCharacterRelationship: { // field return type
    Character: NexusGenRootTypes['MFCharacter'] | null; // MFCharacter
    characterId: number; // Int!
    id: number; // Int!
    relationship: string; // String!
    targetId: number; // Int!
  }
  MFEvent: { // field return type
    World: NexusGenRootTypes['MFWorld'] | null; // MFWorld
    authorId: number | null; // Int
    characterId: number | null; // Int
    description: string | null; // String
    groupId: number | null; // Int
    id: number; // Int!
    locationId: number | null; // Int
    name: string; // String!
    polarity: NexusGenEnums['EventPolarity']; // EventPolarity!
    target: NexusGenEnums['EventTarget']; // EventTarget!
    worldId: number; // Int!
  }
  MFExploration: { // field return type
    Author: NexusGenRootTypes['MFAuthor'] | null; // MFAuthor
    Location: NexusGenRootTypes['MFLocation'] | null; // MFLocation
    Scenes: Array<NexusGenRootTypes['MFExplorationScene'] | null>; // [MFExplorationScene]!
    World: NexusGenRootTypes['MFWorld'] | null; // MFWorld
    authorId: number | null; // Int
    config: string | null; // String
    created: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    description: string | null; // String
    free: boolean | null; // Boolean
    id: number; // Int!
    image: string | null; // String
    lastUpdated: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    locationId: number | null; // Int
    price: number | null; // Float
    public: boolean | null; // Boolean
    publishDate: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    title: string; // String!
    usesAttributes: string | null; // String
    worldId: number; // Int!
  }
  MFExplorationScene: { // field return type
    Exploration: NexusGenRootTypes['MFExploration'] | null; // MFExploration
    authorId: number | null; // Int
    background: string | null; // String
    characters: string | null; // String
    config: string | null; // String
    description: string | null; // String
    explorationId: number; // Int!
    foreground: string | null; // String
    id: number; // Int!
    order: number; // Int!
    title: string; // String!
  }
  MFLibrary: { // field return type
    Book: NexusGenRootTypes['MFBook'] | null; // MFBook
    Exploration: NexusGenRootTypes['MFExploration'] | null; // MFExploration
    Series: NexusGenRootTypes['MFSeries'] | null; // MFSeries
    bookId: number | null; // Int
    explorationId: number | null; // Int
    id: number; // Int!
    order: number; // Int!
    publicPurchase: boolean; // Boolean!
    purchaseDate: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    seriesId: number | null; // Int
    userId: number; // Int!
  }
  MFLocation: { // field return type
    Characters: Array<NexusGenRootTypes['MFCharacter'] | null> | null; // [MFCharacter]
    ChildLocations: Array<NexusGenRootTypes['MFLocation'] | null> | null; // [MFLocation]
    Events: Array<NexusGenRootTypes['MFEvent'] | null> | null; // [MFEvent]
    Groups: Array<NexusGenRootTypes['MFPopulationGroup'] | null> | null; // [MFPopulationGroup]
    ParentLocation: NexusGenRootTypes['MFLocation'] | null; // MFLocation
    World: NexusGenRootTypes['MFWorld'] | null; // MFWorld
    authorId: number | null; // Int
    childLocationCount: number | null; // Int
    climate: NexusGenEnums['Climate'] | null; // Climate
    description: string; // String!
    fauna: NexusGenEnums['Richness'] | null; // Richness
    flora: NexusGenEnums['Richness'] | null; // Richness
    id: number; // Int!
    name: string; // String!
    parentLocationId: number | null; // Int
    type: NexusGenEnums['LocationType']; // LocationType!
    worldId: number; // Int!
  }
  MFPopulationGroup: { // field return type
    Character: Array<NexusGenRootTypes['MFCharacter'] | null> | null; // [MFCharacter]
    Event: Array<NexusGenRootTypes['MFEvent'] | null> | null; // [MFEvent]
    authorId: number | null; // Int
    description: string; // String!
    id: number; // Int!
    locationId: number | null; // Int
    name: string; // String!
    type: NexusGenEnums['GroupType']; // GroupType!
    worldId: number; // Int!
  }
  MFScene: { // field return type
    Links: Array<NexusGenRootTypes['MFSceneContentLink'] | null> | null; // [MFSceneContentLink]
    authorId: number | null; // Int
    chapterId: number; // Int!
    characterId: number | null; // Int
    created: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    description: string | null; // String
    eventContextId: number | null; // Int
    id: number; // Int!
    image: string | null; // String
    order: number; // Int!
    text: string | null; // String
    timelineId: number | null; // Int
    title: string; // String!
    updated: NexusGenScalars['CsDateTime'] | null; // CsDateTime
  }
  MFSceneContentLink: { // field return type
    authorId: number | null; // Int
    bookId: number; // Int!
    chapterId: number | null; // Int
    id: number; // Int!
    originId: number; // Int!
    sceneId: number | null; // Int
    seriesId: number | null; // Int
    text: string; // String!
  }
  MFSearchResult: { // field return type
    books: Array<NexusGenRootTypes['MFBook'] | null>; // [MFBook]!
    series: Array<NexusGenRootTypes['MFSeries'] | null>; // [MFSeries]!
  }
  MFSeries: { // field return type
    Author: NexusGenRootTypes['MFAuthor'] | null; // MFAuthor
    Books: Array<NexusGenRootTypes['MFBook'] | null>; // [MFBook]!
    authorId: number | null; // Int
    created: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    description: string; // String!
    free: boolean | null; // Boolean
    genre: string; // String!
    id: number; // Int!
    image: string | null; // String
    price: number | null; // Float
    public: boolean; // Boolean!
    publishDate: NexusGenScalars['CsDateTime'] | null; // CsDateTime
    title: string; // String!
    updated: NexusGenScalars['CsDateTime'] | null; // CsDateTime
  }
  MFTimeline: { // field return type
    Author: NexusGenRootTypes['MFAuthor'] | null; // MFAuthor
    Scenes: Array<NexusGenRootTypes['MFScene'] | null> | null; // [MFScene]
    TimelineEvents: Array<NexusGenRootTypes['MFTimelineEvent'] | null> | null; // [MFTimelineEvent]
    World: NexusGenRootTypes['MFWorld'] | null; // MFWorld
    authorId: number | null; // Int
    id: number; // Int!
    name: string; // String!
    worldId: number; // Int!
  }
  MFTimelineEvent: { // field return type
    Event: NexusGenRootTypes['MFEvent'] | null; // MFEvent
    Scenes: Array<NexusGenRootTypes['MFScene'] | null> | null; // [MFScene]
    authorId: number | null; // Int
    eventId: number; // Int!
    id: number; // Int!
    order: number; // Int!
    timelineId: number; // Int!
  }
  MFUser: { // field return type
    Books: Array<NexusGenRootTypes['MFBook'] | null> | null; // [MFBook]
    Characters: Array<NexusGenRootTypes['MFCharacter'] | null> | null; // [MFCharacter]
    Series: Array<NexusGenRootTypes['MFSeries'] | null> | null; // [MFSeries]
    Timelines: Array<NexusGenRootTypes['MFTimeline'] | null> | null; // [MFTimeline]
    Worlds: Array<NexusGenRootTypes['MFWorld'] | null> | null; // [MFWorld]
    authSource: NexusGenEnums['Authenticator']; // Authenticator!
    created: NexusGenScalars['CsDateTime']; // CsDateTime!
    displayName: string; // String!
    email: string; // String!
    firstName: string | null; // String
    id: number; // Int!
    image: string | null; // String
    lastName: string | null; // String
    lastSeen: NexusGenScalars['CsDateTime']; // CsDateTime!
    role: NexusGenEnums['UserRole']; // UserRole!
  }
  MFWorld: { // field return type
    ChildWorlds: Array<NexusGenRootTypes['MFWorld'] | null> | null; // [MFWorld]
    Events: Array<NexusGenRootTypes['MFEvent'] | null> | null; // [MFEvent]
    Groups: Array<NexusGenRootTypes['MFPopulationGroup'] | null> | null; // [MFPopulationGroup]
    Locations: Array<NexusGenRootTypes['MFLocation'] | null> | null; // [MFLocation]
    Timelines: Array<NexusGenRootTypes['MFTimeline'] | null> | null; // [MFTimeline]
    authorId: number | null; // Int
    childWorldsCount: number | null; // Int
    description: string; // String!
    id: number; // Int!
    image: string | null; // String
    name: string; // String!
    parentWorldId: number | null; // Int
    public: boolean; // Boolean!
    type: NexusGenEnums['WorldType']; // WorldType!
  }
  Mutation: { // field return type
    deleteBook: NexusGenRootTypes['MFBook'] | null; // MFBook
    deleteChapter: NexusGenRootTypes['MFChapter'] | null; // MFChapter
    deleteCharacter: NexusGenRootTypes['MFCharacter'] | null; // MFCharacter
    deleteContentLink: NexusGenRootTypes['MFSceneContentLink'] | null; // MFSceneContentLink
    deleteEvent: NexusGenRootTypes['MFEvent'] | null; // MFEvent
    deleteExploration: NexusGenRootTypes['MFExploration'] | null; // MFExploration
    deleteExplorationScene: NexusGenRootTypes['MFExplorationScene'] | null; // MFExplorationScene
    deleteLocation: NexusGenRootTypes['MFLocation'] | null; // MFLocation
    deleteRelationship: NexusGenRootTypes['MFCharacterRelationship'] | null; // MFCharacterRelationship
    deleteScene: NexusGenRootTypes['MFScene'] | null; // MFScene
    deleteSeries: NexusGenRootTypes['MFSeries'] | null; // MFSeries
    deleteTimeline: NexusGenRootTypes['MFTimeline'] | null; // MFTimeline
    deleteTimelineEvent: NexusGenRootTypes['MFTimelineEvent'] | null; // MFTimelineEvent
    deleteWorld: NexusGenRootTypes['MFWorld'] | null; // MFWorld
    publishBook: NexusGenRootTypes['MFBook'] | null; // MFBook
    publishSeries: NexusGenRootTypes['MFSeries'] | null; // MFSeries
    updateUser: NexusGenRootTypes['MFAuthor'] | null; // MFAuthor
    upsertBook: NexusGenRootTypes['MFBook'] | null; // MFBook
    upsertChapter: NexusGenRootTypes['MFChapter'] | null; // MFChapter
    upsertCharacter: NexusGenRootTypes['MFCharacter'] | null; // MFCharacter
    upsertContentLinks: Array<NexusGenRootTypes['MFSceneContentLink'] | null> | null; // [MFSceneContentLink]
    upsertEvents: Array<NexusGenRootTypes['MFEvent'] | null> | null; // [MFEvent]
    upsertExploration: NexusGenRootTypes['MFExploration'] | null; // MFExploration
    upsertExplorationScene: NexusGenRootTypes['MFExplorationScene'] | null; // MFExplorationScene
    upsertLocation: NexusGenRootTypes['MFLocation'] | null; // MFLocation
    upsertRelationships: Array<NexusGenRootTypes['MFCharacterRelationship'] | null> | null; // [MFCharacterRelationship]
    upsertScene: NexusGenRootTypes['MFScene'] | null; // MFScene
    upsertSeries: NexusGenRootTypes['MFSeries'] | null; // MFSeries
    upsertTimeline: NexusGenRootTypes['MFTimeline'] | null; // MFTimeline
    upsertTimelineEvents: Array<NexusGenRootTypes['MFTimelineEvent'] | null> | null; // [MFTimelineEvent]
    upsertWorld: NexusGenRootTypes['MFWorld'] | null; // MFWorld
  }
  Note: { // field return type
    Author: NexusGenRootTypes['MFAuthor'] | null; // MFAuthor
    Book: NexusGenRootTypes['MFBook'] | null; // MFBook
    Chapter: NexusGenRootTypes['MFChapter'] | null; // MFChapter
    Character: NexusGenRootTypes['MFCharacter'] | null; // MFCharacter
    Scene: NexusGenRootTypes['MFScene'] | null; // MFScene
    authorId: number; // Int!
    bookId: number | null; // Int
    chapterId: number | null; // Int
    characterId: number | null; // Int
    description: string; // String!
    id: number; // Int!
    image: string | null; // String
    sceneId: number | null; // Int
    title: string; // String!
  }
  Query: { // field return type
    getAuthUser: NexusGenRootTypes['MFAuthor'] | null; // MFAuthor
    getAuthor: NexusGenRootTypes['MFAuthor'] | null; // MFAuthor
    getBookById: NexusGenRootTypes['MFBook'] | null; // MFBook
    getChapterById: NexusGenRootTypes['MFChapter'] | null; // MFChapter
    getCharacterById: NexusGenRootTypes['MFCharacter'] | null; // MFCharacter
    getContentLink: NexusGenRootTypes['MFSceneContentLink'] | null; // MFSceneContentLink
    getEventById: NexusGenRootTypes['MFEvent'] | null; // MFEvent
    getExploration: NexusGenRootTypes['MFExploration'] | null; // MFExploration
    getExplorationScene: NexusGenRootTypes['MFExplorationScene'] | null; // MFExplorationScene
    getLocationById: NexusGenRootTypes['MFLocation'] | null; // MFLocation
    getRelationshipById: NexusGenRootTypes['MFCharacterRelationship'] | null; // MFCharacterRelationship
    getSceneById: NexusGenRootTypes['MFScene'] | null; // MFScene
    getSeriesById: NexusGenRootTypes['MFSeries'] | null; // MFSeries
    getTimelineById: NexusGenRootTypes['MFTimeline'] | null; // MFTimeline
    getWorld: NexusGenRootTypes['MFWorld'] | null; // MFWorld
    getWorldById: NexusGenRootTypes['MFWorld'] | null; // MFWorld
    listBooks: Array<NexusGenRootTypes['MFBook'] | null> | null; // [MFBook]
    listChapters: Array<NexusGenRootTypes['MFChapter'] | null> | null; // [MFChapter]
    listCharacters: Array<NexusGenRootTypes['MFCharacter'] | null> | null; // [MFCharacter]
    listContentLinks: Array<NexusGenRootTypes['MFSceneContentLink'] | null> | null; // [MFSceneContentLink]
    listExplorationScenes: Array<NexusGenRootTypes['MFExplorationScene'] | null> | null; // [MFExplorationScene]
    listExplorations: Array<NexusGenRootTypes['MFExploration'] | null> | null; // [MFExploration]
    listLocations: Array<NexusGenRootTypes['MFLocation'] | null> | null; // [MFLocation]
    listRelationships: Array<NexusGenRootTypes['MFCharacterRelationship'] | null> | null; // [MFCharacterRelationship]
    listScenes: Array<NexusGenRootTypes['MFScene'] | null> | null; // [MFScene]
    listSeries: Array<NexusGenRootTypes['MFSeries'] | null> | null; // [MFSeries]
    listSeriesPublications: Array<NexusGenRootTypes['MFSeries'] | null> | null; // [MFSeries]
    listTimelineEvents: Array<NexusGenRootTypes['MFTimelineEvent'] | null> | null; // [MFTimelineEvent]
    listTimelines: Array<NexusGenRootTypes['MFTimeline'] | null> | null; // [MFTimeline]
    listUserFiles: Array<string | null>; // [String]!
    listWorldEvents: Array<NexusGenRootTypes['MFEvent'] | null> | null; // [MFEvent]
    listWorlds: Array<NexusGenRootTypes['MFWorld'] | null> | null; // [MFWorld]
    searchPublications: NexusGenRootTypes['MFSearchResult'] | null; // MFSearchResult
  }
}

export interface NexusGenFieldTypeNames {
  MFAuthor: { // field return type name
    Books: 'MFBook'
    Series: 'MFSeries'
    Timelines: 'MFTimeline'
    Worlds: 'MFWorld'
    displayName: 'String'
    email: 'String'
    firstName: 'String'
    id: 'Int'
    image: 'String'
    lastName: 'String'
    role: 'UserRole'
  }
  MFBook: { // field return type name
    Author: 'MFAuthor'
    Chapters: 'MFChapter'
    authorId: 'Int'
    created: 'CsDateTime'
    description: 'String'
    free: 'Boolean'
    genre: 'String'
    id: 'Int'
    image: 'String'
    locationId: 'Int'
    order: 'Int'
    price: 'Float'
    public: 'Boolean'
    publishDate: 'CsDateTime'
    seriesId: 'Int'
    title: 'String'
    updated: 'CsDateTime'
    worldId: 'Int'
  }
  MFChapter: { // field return type name
    Author: 'MFAuthor'
    Links: 'MFSceneContentLink'
    Scenes: 'MFScene'
    authorId: 'Int'
    bookId: 'Int'
    created: 'CsDateTime'
    description: 'String'
    id: 'Int'
    image: 'String'
    order: 'Int'
    status: 'ChapterStatus'
    title: 'String'
    updated: 'CsDateTime'
  }
  MFCharacter: { // field return type name
    CharacterRelationship: 'MFCharacterRelationship'
    World: 'MFWorld'
    authorId: 'Int'
    description: 'String'
    groupId: 'Int'
    id: 'Int'
    image: 'String'
    locationId: 'Int'
    name: 'String'
    worldId: 'Int'
  }
  MFCharacterRelationship: { // field return type name
    Character: 'MFCharacter'
    characterId: 'Int'
    id: 'Int'
    relationship: 'String'
    targetId: 'Int'
  }
  MFEvent: { // field return type name
    World: 'MFWorld'
    authorId: 'Int'
    characterId: 'Int'
    description: 'String'
    groupId: 'Int'
    id: 'Int'
    locationId: 'Int'
    name: 'String'
    polarity: 'EventPolarity'
    target: 'EventTarget'
    worldId: 'Int'
  }
  MFExploration: { // field return type name
    Author: 'MFAuthor'
    Location: 'MFLocation'
    Scenes: 'MFExplorationScene'
    World: 'MFWorld'
    authorId: 'Int'
    config: 'String'
    created: 'CsDateTime'
    description: 'String'
    free: 'Boolean'
    id: 'Int'
    image: 'String'
    lastUpdated: 'CsDateTime'
    locationId: 'Int'
    price: 'Float'
    public: 'Boolean'
    publishDate: 'CsDateTime'
    title: 'String'
    usesAttributes: 'String'
    worldId: 'Int'
  }
  MFExplorationScene: { // field return type name
    Exploration: 'MFExploration'
    authorId: 'Int'
    background: 'String'
    characters: 'String'
    config: 'String'
    description: 'String'
    explorationId: 'Int'
    foreground: 'String'
    id: 'Int'
    order: 'Int'
    title: 'String'
  }
  MFLibrary: { // field return type name
    Book: 'MFBook'
    Exploration: 'MFExploration'
    Series: 'MFSeries'
    bookId: 'Int'
    explorationId: 'Int'
    id: 'Int'
    order: 'Int'
    publicPurchase: 'Boolean'
    purchaseDate: 'CsDateTime'
    seriesId: 'Int'
    userId: 'Int'
  }
  MFLocation: { // field return type name
    Characters: 'MFCharacter'
    ChildLocations: 'MFLocation'
    Events: 'MFEvent'
    Groups: 'MFPopulationGroup'
    ParentLocation: 'MFLocation'
    World: 'MFWorld'
    authorId: 'Int'
    childLocationCount: 'Int'
    climate: 'Climate'
    description: 'String'
    fauna: 'Richness'
    flora: 'Richness'
    id: 'Int'
    name: 'String'
    parentLocationId: 'Int'
    type: 'LocationType'
    worldId: 'Int'
  }
  MFPopulationGroup: { // field return type name
    Character: 'MFCharacter'
    Event: 'MFEvent'
    authorId: 'Int'
    description: 'String'
    id: 'Int'
    locationId: 'Int'
    name: 'String'
    type: 'GroupType'
    worldId: 'Int'
  }
  MFScene: { // field return type name
    Links: 'MFSceneContentLink'
    authorId: 'Int'
    chapterId: 'Int'
    characterId: 'Int'
    created: 'CsDateTime'
    description: 'String'
    eventContextId: 'Int'
    id: 'Int'
    image: 'String'
    order: 'Int'
    text: 'String'
    timelineId: 'Int'
    title: 'String'
    updated: 'CsDateTime'
  }
  MFSceneContentLink: { // field return type name
    authorId: 'Int'
    bookId: 'Int'
    chapterId: 'Int'
    id: 'Int'
    originId: 'Int'
    sceneId: 'Int'
    seriesId: 'Int'
    text: 'String'
  }
  MFSearchResult: { // field return type name
    books: 'MFBook'
    series: 'MFSeries'
  }
  MFSeries: { // field return type name
    Author: 'MFAuthor'
    Books: 'MFBook'
    authorId: 'Int'
    created: 'CsDateTime'
    description: 'String'
    free: 'Boolean'
    genre: 'String'
    id: 'Int'
    image: 'String'
    price: 'Float'
    public: 'Boolean'
    publishDate: 'CsDateTime'
    title: 'String'
    updated: 'CsDateTime'
  }
  MFTimeline: { // field return type name
    Author: 'MFAuthor'
    Scenes: 'MFScene'
    TimelineEvents: 'MFTimelineEvent'
    World: 'MFWorld'
    authorId: 'Int'
    id: 'Int'
    name: 'String'
    worldId: 'Int'
  }
  MFTimelineEvent: { // field return type name
    Event: 'MFEvent'
    Scenes: 'MFScene'
    authorId: 'Int'
    eventId: 'Int'
    id: 'Int'
    order: 'Int'
    timelineId: 'Int'
  }
  MFUser: { // field return type name
    Books: 'MFBook'
    Characters: 'MFCharacter'
    Series: 'MFSeries'
    Timelines: 'MFTimeline'
    Worlds: 'MFWorld'
    authSource: 'Authenticator'
    created: 'CsDateTime'
    displayName: 'String'
    email: 'String'
    firstName: 'String'
    id: 'Int'
    image: 'String'
    lastName: 'String'
    lastSeen: 'CsDateTime'
    role: 'UserRole'
  }
  MFWorld: { // field return type name
    ChildWorlds: 'MFWorld'
    Events: 'MFEvent'
    Groups: 'MFPopulationGroup'
    Locations: 'MFLocation'
    Timelines: 'MFTimeline'
    authorId: 'Int'
    childWorldsCount: 'Int'
    description: 'String'
    id: 'Int'
    image: 'String'
    name: 'String'
    parentWorldId: 'Int'
    public: 'Boolean'
    type: 'WorldType'
  }
  Mutation: { // field return type name
    deleteBook: 'MFBook'
    deleteChapter: 'MFChapter'
    deleteCharacter: 'MFCharacter'
    deleteContentLink: 'MFSceneContentLink'
    deleteEvent: 'MFEvent'
    deleteExploration: 'MFExploration'
    deleteExplorationScene: 'MFExplorationScene'
    deleteLocation: 'MFLocation'
    deleteRelationship: 'MFCharacterRelationship'
    deleteScene: 'MFScene'
    deleteSeries: 'MFSeries'
    deleteTimeline: 'MFTimeline'
    deleteTimelineEvent: 'MFTimelineEvent'
    deleteWorld: 'MFWorld'
    publishBook: 'MFBook'
    publishSeries: 'MFSeries'
    updateUser: 'MFAuthor'
    upsertBook: 'MFBook'
    upsertChapter: 'MFChapter'
    upsertCharacter: 'MFCharacter'
    upsertContentLinks: 'MFSceneContentLink'
    upsertEvents: 'MFEvent'
    upsertExploration: 'MFExploration'
    upsertExplorationScene: 'MFExplorationScene'
    upsertLocation: 'MFLocation'
    upsertRelationships: 'MFCharacterRelationship'
    upsertScene: 'MFScene'
    upsertSeries: 'MFSeries'
    upsertTimeline: 'MFTimeline'
    upsertTimelineEvents: 'MFTimelineEvent'
    upsertWorld: 'MFWorld'
  }
  Note: { // field return type name
    Author: 'MFAuthor'
    Book: 'MFBook'
    Chapter: 'MFChapter'
    Character: 'MFCharacter'
    Scene: 'MFScene'
    authorId: 'Int'
    bookId: 'Int'
    chapterId: 'Int'
    characterId: 'Int'
    description: 'String'
    id: 'Int'
    image: 'String'
    sceneId: 'Int'
    title: 'String'
  }
  Query: { // field return type name
    getAuthUser: 'MFAuthor'
    getAuthor: 'MFAuthor'
    getBookById: 'MFBook'
    getChapterById: 'MFChapter'
    getCharacterById: 'MFCharacter'
    getContentLink: 'MFSceneContentLink'
    getEventById: 'MFEvent'
    getExploration: 'MFExploration'
    getExplorationScene: 'MFExplorationScene'
    getLocationById: 'MFLocation'
    getRelationshipById: 'MFCharacterRelationship'
    getSceneById: 'MFScene'
    getSeriesById: 'MFSeries'
    getTimelineById: 'MFTimeline'
    getWorld: 'MFWorld'
    getWorldById: 'MFWorld'
    listBooks: 'MFBook'
    listChapters: 'MFChapter'
    listCharacters: 'MFCharacter'
    listContentLinks: 'MFSceneContentLink'
    listExplorationScenes: 'MFExplorationScene'
    listExplorations: 'MFExploration'
    listLocations: 'MFLocation'
    listRelationships: 'MFCharacterRelationship'
    listScenes: 'MFScene'
    listSeries: 'MFSeries'
    listSeriesPublications: 'MFSeries'
    listTimelineEvents: 'MFTimelineEvent'
    listTimelines: 'MFTimeline'
    listUserFiles: 'String'
    listWorldEvents: 'MFEvent'
    listWorlds: 'MFWorld'
    searchPublications: 'MFSearchResult'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    deleteBook: { // args
      id: number; // Int!
    }
    deleteChapter: { // args
      id: number; // Int!
    }
    deleteCharacter: { // args
      id: number; // Int!
    }
    deleteContentLink: { // args
      id: number; // Int!
    }
    deleteEvent: { // args
      id: number; // Int!
    }
    deleteExploration: { // args
      id: number; // Int!
    }
    deleteExplorationScene: { // args
      id: number; // Int!
    }
    deleteLocation: { // args
      id: number; // Int!
    }
    deleteRelationship: { // args
      id: number; // Int!
    }
    deleteScene: { // args
      id: number; // Int!
    }
    deleteSeries: { // args
      id: number; // Int!
    }
    deleteTimeline: { // args
      id: number; // Int!
    }
    deleteTimelineEvent: { // args
      id: number; // Int!
    }
    deleteWorld: { // args
      id: number; // Int!
    }
    publishBook: { // args
      id: number; // Int!
    }
    publishSeries: { // args
      id: number; // Int!
    }
    updateUser: { // args
      data: NexusGenInputs['MFUserUpsertInput']; // MFUserUpsertInput!
      id: number; // Int!
    }
    upsertBook: { // args
      data: NexusGenInputs['MFBookUpsertInput']; // MFBookUpsertInput!
    }
    upsertChapter: { // args
      data: NexusGenInputs['MFChapterUpsertInput']; // MFChapterUpsertInput!
    }
    upsertCharacter: { // args
      data: NexusGenInputs['MFCharacterUpsertInput']; // MFCharacterUpsertInput!
    }
    upsertContentLinks: { // args
      data?: NexusGenInputs['MFContentLinkUpsertInput'][] | null; // [MFContentLinkUpsertInput!]
    }
    upsertEvents: { // args
      data: Array<NexusGenInputs['MFEventUpsertInput'] | null>; // [MFEventUpsertInput]!
    }
    upsertExploration: { // args
      data: NexusGenInputs['MFExplorationUpsertInput']; // MFExplorationUpsertInput!
    }
    upsertExplorationScene: { // args
      data: NexusGenInputs['MFExplorationSceneUpsertInput']; // MFExplorationSceneUpsertInput!
    }
    upsertLocation: { // args
      data: NexusGenInputs['MFLocationUpsertInput']; // MFLocationUpsertInput!
    }
    upsertRelationships: { // args
      data: NexusGenInputs['MFRelationshipUpsertInput'][]; // [MFRelationshipUpsertInput!]!
    }
    upsertScene: { // args
      data: NexusGenInputs['MFSceneUpsertInput']; // MFSceneUpsertInput!
    }
    upsertSeries: { // args
      data: NexusGenInputs['MFSeriesUpsertInput']; // MFSeriesUpsertInput!
    }
    upsertTimeline: { // args
      data: NexusGenInputs['MFTimelineUpsertInput']; // MFTimelineUpsertInput!
    }
    upsertTimelineEvents: { // args
      events?: NexusGenInputs['MFTimelineEventUpsertInput'][] | null; // [MFTimelineEventUpsertInput!]
      id: number; // Int!
    }
    upsertWorld: { // args
      data: NexusGenInputs['MFWorldUpsertInput']; // MFWorldUpsertInput!
    }
  }
  Query: {
    getAuthor: { // args
      id: number; // Int!
    }
    getBookById: { // args
      id: number; // Int!
    }
    getChapterById: { // args
      id: number; // Int!
    }
    getCharacterById: { // args
      id: number; // Int!
    }
    getContentLink: { // args
      id: number; // Int!
    }
    getEventById: { // args
      id: number; // Int!
    }
    getExploration: { // args
      id: number; // Int!
    }
    getExplorationScene: { // args
      id: number; // Int!
    }
    getLocationById: { // args
      id: number; // Int!
    }
    getRelationshipById: { // args
      id: number; // Int!
    }
    getSceneById: { // args
      id: number; // Int!
    }
    getSeriesById: { // args
      id: number; // Int!
    }
    getTimelineById: { // args
      id: number; // Int!
    }
    getWorld: { // args
      id: number; // Int!
    }
    getWorldById: { // args
      id: number; // Int!
    }
    listBooks: { // args
      authorId?: number | null; // Int
      description?: string | null; // String
      free?: boolean | null; // Boolean
      genre?: string | null; // String
      public?: boolean | null; // Boolean
      seriesId?: number | null; // Int
      title?: string | null; // String
    }
    listChapters: { // args
      authorId?: number | null; // Int
      bookId: number; // Int!
      description?: string | null; // String
      id?: number[] | null; // [Int!]
      title?: string | null; // String
    }
    listCharacters: { // args
      authorId?: number | null; // Int
      description?: string | null; // String
      id?: number | null; // Int
      name?: string | null; // String
      worldId?: number | null; // Int
    }
    listContentLinks: { // args
      authorId?: number | null; // Int
      bookId?: number | null; // Int
      chapterId?: number | null; // Int
      sceneId?: number | null; // Int
      seriesId?: number | null; // Int
      text?: string | null; // String
    }
    listExplorationScenes: { // args
      explorationId: number; // Int!
    }
    listExplorations: { // args
      attributes?: string[] | null; // [String!]
      authorId?: number | null; // Int
      description?: string | null; // String
      freeOnly?: boolean | null; // Boolean
      id?: number | null; // Int
      inLibraryOnly?: boolean | null; // Boolean
      locationId?: number | null; // Int
      maxPrice?: number | null; // Int
      minPrice?: number | null; // Int
      publicOnly?: boolean | null; // Boolean
      publishedOnly?: boolean | null; // Boolean
      title?: string | null; // String
      worldId?: number | null; // Int
    }
    listLocations: { // args
      authorId?: number | null; // Int
      description?: string | null; // String
      id?: number | null; // Int
      name?: string | null; // String
      worldId: number; // Int!
    }
    listRelationships: { // args
      characterId?: number | null; // Int
      id?: number | null; // Int
      relationship?: string | null; // String
      targetId?: number | null; // Int
    }
    listScenes: { // args
      authorId?: number | null; // Int
      chapterId: number; // Int!
      description?: string | null; // String
      id?: number[] | null; // [Int!]
      text?: string | null; // String
      title?: string | null; // String
    }
    listSeries: { // args
      authorId?: number | null; // Int
      description?: string | null; // String
      freeOnly?: boolean | null; // Boolean
      genre?: string | null; // String
      publicOnly?: boolean | null; // Boolean
      title?: string | null; // String
    }
    listSeriesPublications: { // args
      authorId?: number | null; // Int
      description?: string | null; // String
      genre?: string | null; // String
      title?: string | null; // String
    }
    listTimelineEvents: { // args
      timelineId: number; // Int!
    }
    listTimelines: { // args
      authorId?: number | null; // Int
      name?: string | null; // String
      worldId?: number | null; // Int
    }
    listUserFiles: { // args
      category: string; // String!
    }
    listWorldEvents: { // args
      authorId?: number | null; // Int
      characterId?: number | null; // Int
      description?: string | null; // String
      groupId?: number | null; // Int
      locationId?: number | null; // Int
      name?: string | null; // String
      polarity?: NexusGenEnums['EventPolarity'] | null; // EventPolarity
      target?: NexusGenEnums['EventTarget'] | null; // EventTarget
      worldId?: number | null; // Int
    }
    listWorlds: { // args
      authorId?: number | null; // Int
      description?: string | null; // String
      id?: number | null; // Int
      name?: string | null; // String
      parentWorldId?: number | null; // Int
      parentsOnly?: boolean | null; // Boolean
      public: boolean | null; // Boolean
    }
    searchPublications: { // args
      authorId?: number | null; // Int
      description?: string | null; // String
      freeOnly?: boolean | null; // Boolean
      genre?: string | null; // String
      seriesId?: number | null; // Int
      title?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: DBContext;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}